#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:assert", "assert")

#@ def admin_client_credentials():
oauth:
  clients:
    admin:
      secret: #@ data.values.admin.client_secret or assert.fail("admin.client_secret is required")
#@ end

#@ def admin_client_secret():
apiVersion: v1
kind: Secret
metadata:
  name: uaa-admin-client-credentials
type: Opaque
stringData:
  admin_client_credentials.yml: #@ yaml.encode(admin_client_credentials())
#@ end

#@ if not data.values.include_default_profile:
--- #@ admin_client_secret()
#@ end
