#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def database_credentials():
database:
  username: #@ data.values.database.username
  password: #@ data.values.database.password
#@ end

---
apiVersion: v1
kind: Secret
metadata:
  name: uaa-database-credentials
type: Opaque
stringData:
  database_credentials.yml: #@ yaml.encode(database_credentials())
